import VideosOnHome from "../videosOnHome/VideosOnHome";
export const RoutesComponentsArray = [
  <VideosOnHome />,
  <h1>Explore</h1>,
  <h1>Subscribtions</h1>,
  <h1>Library</h1>,
  <h1>History</h1>,
  <h1>Music</h1>,
  <h1>Sports </h1>,
  <h1>Gaming</h1>,
  <h1>News</h1>,
  <h1>Live</h1>,
  <h1>360 videos</h1>,
  <h1>Browse channels</h1>,
  <h1>Live</h1>,
  <h1>Settings</h1>,
  <h1>Report</h1>,
  <h1>Help</h1>,
  <h1>send feedback</h1>,
];
